[project]
name = "get_channels"
version = "0.1.0"
description = "simple slack tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "requests>=2.32.3",
    "slack_sdk>=3.36.0",
]
